// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ygzhwgmpctarsemrahnq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlnemh3Z21wY3RhcnNlbXJhaG5xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNzU5NjUsImV4cCI6MjA2Mzc1MTk2NX0.4kQ2XmO8q36qeSCBMwYFw6XpC9nhEeqLAT8GLGzZmZM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);